# # 使用 Node.js 18 Alpine 作为基础镜像
# FROM node:18-alpine

# # 设置工作目录
# WORKDIR /usr/src/app

# # 设置时区
# ENV TZ=Asia/Shanghai

# # 复制 package.json 和 package-lock.json (如果存在)
# COPY package*.json ./

# # 安装依赖
# RUN npm install

# # 复制项目文件
# COPY . .

# # 暴露端口
# EXPOSE 8080

# # 启动命令
# CMD ["npm", "run", "start"]

# =========================================

# 使用 Node.js 18 Alpine 作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /usr/src/app

# 设置时区
ENV TZ=Asia/Shanghai

# 配置 npm 使用淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com

# 复制 package.json 和 package-lock.json (如果存在)
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY . .

# 暴露端口
EXPOSE 8080

# 启动命令
CMD ["npm", "run", "start"]