version: '3.8'

services:
  my-home-server-express-ts:
    container_name: my-home-server-express-ts
    build: .  # 使用当前目录下的 Dockerfile 构建镜像
    restart: always
    ports:
      - "8080:8080"
    mem_limit: 1G
    memswap_limit: 1.5G
    logging:
      options:
        max-size: "10m"
        max-file: "3"