# 注意 不再使用此方式进行部署 而是使用README.md中的方式进行部署
FROM node:20.17.0-alpine

# 设置工作目录
WORKDIR /usr/src/app

# 将本地代码复制到容器中
COPY . .

# 安装依赖
RUN npm install

# 启动应用 注意 不要使用dev！！否则生成 prisma 客户端的过程中会报依赖错误
CMD ["npm", "run", "prod"]

# 记得给权限chmod -R 777 ./*
# sudo docker build -t my-home-server-express-js-image .
# sudo docker run -d --restart=always --name my-express-app -p 8080:8080 -v /myProject/my-home-server-express-js:/usr/src/app my-home-server-express-js-image

# 小贴士 使用 pm2 + dockerfile 时候 需要注意使用 pm2-runtime 而不是 pm2
# 具体内容查看 https://blog.happywinter.cn/frontend/docker_pm2.html#%E5%8E%9F%E5%9B%A0