# 使用 Node.js 22-slim 版本的镜像
FROM node:22-slim
# 生成一个工作目录，在这个目录下执行命令
WORKDIR /app
# 复制 package.json 到工作目录
COPY package.json .
# 安装依赖
RUN npm install
# 复制整个项目到工作目录
COPY . .
# 暴露端口
EXPOSE 8080
# 启动命令
CMD ["npm", "run", "dev"]

# 创建容器并自启动
# docker build -t my-node-app .

# docker run -d -p 8080:8080 --name my-node-app-container --restart always my-node-app