# 执行docker compose up -d即可

version: '3.8'

services:
  # 后端服务
  my-home-server-express-ts:
    container_name: my-home-server-express-ts
    image: node:18-alpine
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./my-home-server-express-ts:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 1G
    memswap_limit: 1.5G
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command: sh -c "npm install && npm run start"
    networks:
      - my-home-network

  # 前端服务
  my-home-client-vue-ts:
    image: nginx:latest
    container_name: my-home-client-vue-ts
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 1G
    memswap_limit: 1.5G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./my-home-client-vue-ts/myNginxConf/nginx.conf:/etc/nginx/nginx.conf
      - ./my-home-client-vue-ts/myNginxConf/cert:/etc/nginx/cert
      - ./my-home-client-vue-ts/dist:/usr/share/nginx/html
      - ./my-home-client-vue-ts/package.json:/usr/share/nginx/html/package.json
      - ./my-home-client-vue-ts/docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - my-home-network
    depends_on:
      - my-home-server-express-ts

  # 数据库服务
  db-service:
    image: node:18-alpine
    container_name: db-service
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./db-service:/usr/src/app
    environment:
      - TZ=Asia/Shanghai
    cpus: 2
    mem_limit: 1G
    memswap_limit: 1.5G
    logging:
      options:
        max-size: 10m
        max-file: '3'
    command: sh -c "npm install && npm run start"
    networks:
      - my-home-network

networks:
  my-home-network:
    driver: bridge