FROM node:alpine
WORKDIR /app

# 设置国内镜像源（可替换为你喜欢的镜像）
RUN npm config set registry https://registry.npmmirror.com

COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 8082
CMD ["npm", "run", "start:prod"]