# 基于 Node.js 官方镜像
FROM node:18

# 创建工作目录
WORKDIR /app

# 将项目文件复制到工作目录
COPY . /app

# 安装依赖
RUN npm install

# 暴露端口-暂时不需要
# EXPOSE 5672

# 启动服务器
CMD ["npm", "run", "prod"]

# chmod -R 777 ./*
# 构建镜像
# docker build -t db-service-image .
# 运行容器
# docker run -d db-service-image