# 定义全局配置
user nginx;  # 指定 Nginx 运行的用户
worker_processes auto;  # 自动根据 CPU 核心数分配工作进程

# 定义错误日志路径
error_log /var/log/nginx/error.log warn;

# 定义 PID 文件路径
pid /var/run/nginx.pid;

# 定义 HTTP 服务器
events {
    worker_connections 1024;  # 每个工作进程的最大连接数
}

http {
    # 定义日志格式
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    # 定义访问日志路径
    access_log /var/log/nginx/access.log main;

    # 定义默认字符集
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # 定义 MIME 类型
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 定义服务器
    server {
        listen 80;  # 监听 80 端口
        server_name home;  # 定义服务器名称

        # 定义静态文件根目录
        root /usr/share/nginx/html;
        index index.html index.htm;  # 定义默认索引文件

        # 处理静态文件请求
        location / {
            try_files $uri $uri/ =404;  # 尝试提供请求的文件，如果不存在则返回 404
        }

        # 错误页面
        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;

        # 定义错误页面的路径
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}