version: '3.8'

services:
  vue-app:
    build: .
    ports:
      - "81:81" # 管理端使用81端口，阿里云安全组记得开端口！！
      - "444:444"  # 管理端使用444端口，阿里云安全组记得开端口！！
    restart: unless-stopped

# 访问地址：https://www.wbeishangw.top:444/