# 基于官方 Nginx 镜像
FROM nginx:latest

# 将本地的配置文件复制到容器的 /etc/nginx 目录
COPY myNginxConf/ /etc/nginx/

# 将本地的 HTML 文件复制到容器的 /usr/share/nginx/html 目录
# COPY myNginxHtml/ /usr/share/nginx/html/
COPY dist/ /usr/share/nginx/html/

# 暴露 80 和 443 端口
EXPOSE 80 443

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]

# 权限记得设置chmod -R 777 ./*
# 构建镜像(注意 构建镜像后再将打包后的文件复制到myNginxConf是不会生效的!需要在构建镜像前复制)：docker build -t my-home-client-vue-js-image .
# 运行容器：docker run -d --name my-home-client-vue-js-container --restart=always -p 80:80 -p 443:443 my-home-client-vue-js-image

# 删除悬空镜像 docker rmi -f $(docker images -f "dangling=true" -q)